server:
  port: 8081

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minio_bucket?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:cn/zekaio/api/mapper/*.xml
  type-aliases-package: cn.zekaio.minio.pojo